import './globals.css'
import { Montserrat } from 'next/font/google'
import Navbar from './Navbar'
import Footer from './Footer'

const montserrat = Montserrat({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-montserrat'
})

export const metadata = {
  title: '🎥 TMDB Demo 🎞',
  description: 'Generated by create next app',
  colorScheme: 'dark'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html data-theme="dark" lang="en">
      <body>
        <Navbar />
        <div className={`${montserrat.className} mx-32 my-12`}>
          {children}
        </div>
        <Footer />
      </body>
      {/* <body className={`${montserrat.className} mx-32 my-12`}>
        {children}
      </body> */}
    </html>
  )
}
